import app.models.usuario
import app.models.imovel
import app.models.favorito
import app.models.proprietario
import app.models.mandato
import app.models.lead
import app.models.agendamento
import app.models.disponibilidade
import app.models.responsavel
import app.models.perfil_comprador
import app.models.atividade
import app.models.midia
import app.models.proposta
import app.models.visualizacao_imovel
import app.models.comissao
import app.models.documento
import app.models.whatsapp
import app.models.configuracao
import app.models.pagamento
import app.models.cupom
