"""add_performance_indexes

Revision ID: 88d887a83afb
Revises: 0002
Create Date: 2026-03-30 18:13:17.352110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d887a83afb'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_area'), 'properties', ['area'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_area'), table_name='properties')
    # ### end Alembic commands ###
