"""Add plan_type and expires_at to user

Revision ID: a37d4d92facc
Revises: 88d887a83afb
Create Date: 2026-04-06 08:25:02.740911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37d4d92facc'
down_revision: Union[str, None] = '88d887a83afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_plan_type'), 'users', ['plan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_plan_type'), table_name='users')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'plan_type')
    # ### end Alembic commands ###
