"""Add missing tables

Revision ID: caea2bc6cf91
Revises: 0003
Create Date: 2026-04-10 14:44:26.628137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'caea2bc6cf91'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('listing_type', sa.String(), nullable=True),
    sa.Column('min_bedrooms', sa.Integer(), nullable=True),
    sa.Column('min_bathrooms', sa.Integer(), nullable=True),
    sa.Column('min_garage_spaces', sa.Integer(), nullable=True),
    sa.Column('financing_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_buyer_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_profiles'))
    )
    op.create_index(op.f('ix_buyer_profiles_id'), 'buyer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], name=op.f('fk_owners_broker_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=False)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('nivel_interesse', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_favorites_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], name=op.f('fk_leads_broker_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_leads_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('commission_percentage', sa.Float(), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], name=op.f('fk_mandates_broker_id_users')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_mandates_owner_id_owners')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_mandates_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandates'))
    )
    op.create_index(op.f('ix_mandates_id'), 'mandates', ['id'], unique=False)
    op.create_table('property_assignments',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_assignments_property_id_properties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_property_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('property_id', 'user_id', name=op.f('pk_property_assignments'))
    )
    op.create_table('property_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_availability_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_availability'))
    )
    op.create_index(op.f('ix_property_availability_id'), 'property_availability', ['id'], unique=False)
    op.create_table('property_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_media_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_media'))
    )
    op.create_index(op.f('ix_property_media_id'), 'property_media', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=True),
    sa.Column('buyer_phone', sa.String(), nullable=True),
    sa.Column('proposed_price', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('financing_percentage', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], name=op.f('fk_proposals_broker_id_users')),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('fk_proposals_buyer_user_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_proposals_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    op.create_index(op.f('ix_proposals_buyer_user_id'), 'proposals', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_property_id'), 'proposals', ['property_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_table('comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('corretor_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('valor_imovel', sa.Float(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.Column('valor_comissao', sa.Float(), nullable=False),
    sa.Column('status_pagamento', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['users.id'], name=op.f('fk_comissoes_agency_id_users')),
    sa.ForeignKeyConstraint(['corretor_id'], ['users.id'], name=op.f('fk_comissoes_corretor_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_comissoes_property_id_properties')),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_comissoes_proposal_id_proposals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comissoes'))
    )
    op.create_index(op.f('ix_comissoes_corretor_id'), 'comissoes', ['corretor_id'], unique=False)
    op.create_index(op.f('ix_comissoes_id'), 'comissoes', ['id'], unique=False)
    op.create_index(op.f('ix_comissoes_property_id'), 'comissoes', ['property_id'], unique=False)
    op.create_index(op.f('ix_comissoes_proposal_id'), 'comissoes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_comissoes_status_pagamento'), 'comissoes', ['status_pagamento'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_activities_lead_id_leads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_activities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activities'))
    )
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.drop_table('spatial_ref_sys')
    op.drop_table('property_views_2026_05')
    op.add_column('appointments', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('appointments', 'property_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('appointments', 'broker_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_appt_broker'), table_name='appointments')
    op.drop_index(op.f('idx_appt_dates'), table_name='appointments')
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.drop_constraint(op.f('appointments_visitor_user_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_appointments_buyer_id_users'), 'appointments', 'users', ['buyer_id'], ['id'])
    op.drop_column('appointments', 'visitor_user_id')
    op.add_column('properties', sa.Column('listing_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('property_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('properties', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('properties', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'full_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('properties', 'status',
               existing_type=postgresql.ENUM('active', 'pending', 'archived', 'suspended', name='property_status'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::property_status"))
    op.alter_column('properties', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('properties', 'actual_owner_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('properties', 'commission_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'market_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('properties', 'valor_aluguel',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'atributos_extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_prop_attr_json'), table_name='properties', postgresql_using='gin')
    op.drop_index(op.f('idx_prop_city_neigh'), table_name='properties')
    op.drop_index(op.f('idx_prop_location'), table_name='properties', postgresql_using='gist')
    op.drop_index(op.f('idx_prop_price'), table_name='properties')
    op.drop_index(op.f('idx_prop_status_type'), table_name='properties')
    op.drop_index(op.f('idx_prop_text_search'), table_name='properties', postgresql_using='gin')
    op.drop_constraint(op.f('properties_source_url_key'), 'properties', type_='unique')
    op.create_index(op.f('ix_properties_area'), 'properties', ['area'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_listing_type'), 'properties', ['listing_type'], unique=False)
    op.create_index(op.f('ix_properties_neighborhood'), 'properties', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_title'), 'properties', ['title'], unique=False)
    op.create_index(op.f('ix_properties_views_count'), 'properties', ['views_count'], unique=False)
    op.create_unique_constraint(op.f('uq_properties_source_url'), 'properties', ['source_url'])
    op.drop_constraint(op.f('properties_actual_owner_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('fk_properties_actual_owner_id_owners'), 'properties', 'owners', ['actual_owner_id'], ['id'])
    op.drop_column('properties', 'location')
    op.drop_column('properties', 'list_type')
    op.drop_column('properties', 'text_search')
    op.drop_column('properties', 'type_prop')
    op.alter_column('property_views', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('property_views', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('property_views', 'property_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('property_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_property_views_id'), 'property_views', ['id'], unique=False)
    op.create_index(op.f('ix_property_views_property_id'), 'property_views', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_views_user_id'), 'property_views', ['user_id'], unique=False)
    op.create_unique_constraint('uq_property_views_user_property', 'property_views', ['user_id', 'property_id'])
    op.create_foreign_key(op.f('fk_property_views_user_id_users'), 'property_views', 'users', ['user_id'], ['id'])
    op.drop_column('property_views', 'ip_address')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'broker', 'agency', 'admin', name='user_role'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.alter_column('users', 'plan_type',
               existing_type=postgresql.ENUM('free', 'pro', 'premium', name='user_plan'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::user_plan"))
    op.alter_column('users', 'parent_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_plan_type'), 'users', ['plan_type'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_plan_type'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'plan_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('free', 'pro', 'premium', name='user_plan'),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::user_plan"))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'broker', 'agency', 'admin', name='user_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::user_role"))
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.add_column('property_views', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_property_views_user_id_users'), 'property_views', type_='foreignkey')
    op.drop_constraint('uq_property_views_user_property', 'property_views', type_='unique')
    op.drop_index(op.f('ix_property_views_user_id'), table_name='property_views')
    op.drop_index(op.f('ix_property_views_property_id'), table_name='property_views')
    op.drop_index(op.f('ix_property_views_id'), table_name='property_views')
    op.alter_column('property_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_views', 'property_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('property_views', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('property_views', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('properties', sa.Column('type_prop', postgresql.ENUM('casa', 'apartamento', 'terreno', 'comercial', name='property_type'), server_default=sa.text("'apartamento'::property_type"), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('text_search', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('list_type', postgresql.ENUM('venda', 'aluguel', 'temporada', name='listing_type'), server_default=sa.text("'venda'::listing_type"), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('location', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_properties_actual_owner_id_owners'), 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_actual_owner_id_fkey'), 'properties', 'users', ['actual_owner_id'], ['id'])
    op.drop_constraint(op.f('uq_properties_source_url'), 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_views_count'), table_name='properties')
    op.drop_index(op.f('ix_properties_title'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_neighborhood'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_area'), table_name='properties')
    op.create_unique_constraint(op.f('properties_source_url_key'), 'properties', ['source_url'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_prop_text_search'), 'properties', ['text_search'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_prop_status_type'), 'properties', ['status', 'list_type'], unique=False)
    op.create_index(op.f('idx_prop_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('idx_prop_location'), 'properties', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_prop_city_neigh'), 'properties', ['city', 'neighborhood'], unique=False)
    op.create_index(op.f('idx_prop_attr_json'), 'properties', ['atributos_extras'], unique=False, postgresql_using='gin')
    op.alter_column('properties', 'atributos_extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('properties', 'valor_aluguel',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('properties', 'market_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('properties', 'commission_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('properties', 'actual_owner_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('properties', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('properties', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'pending', 'archived', 'suspended', name='property_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::property_status"))
    op.alter_column('properties', 'full_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('properties', 'area',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('properties', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('properties', 'last_analysis_at')
    op.drop_column('properties', 'property_type')
    op.drop_column('properties', 'listing_type')
    op.add_column('appointments', sa.Column('visitor_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_appointments_buyer_id_users'), 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_visitor_user_id_fkey'), 'appointments', 'users', ['visitor_user_id'], ['id'])
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.create_index(op.f('idx_appt_dates'), 'appointments', ['visit_date'], unique=False)
    op.create_index(op.f('idx_appt_broker'), 'appointments', ['broker_id'], unique=False)
    op.alter_column('appointments', 'broker_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('appointments', 'property_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('appointments', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('appointments', 'buyer_id')
    op.create_table('property_views_2026_05',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('property_views_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'viewed_at', name=op.f('property_views_2026_05_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_comissoes_status_pagamento'), table_name='comissoes')
    op.drop_index(op.f('ix_comissoes_proposal_id'), table_name='comissoes')
    op.drop_index(op.f('ix_comissoes_property_id'), table_name='comissoes')
    op.drop_index(op.f('ix_comissoes_id'), table_name='comissoes')
    op.drop_index(op.f('ix_comissoes_corretor_id'), table_name='comissoes')
    op.drop_table('comissoes')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_property_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_buyer_user_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_property_media_id'), table_name='property_media')
    op.drop_table('property_media')
    op.drop_index(op.f('ix_property_availability_id'), table_name='property_availability')
    op.drop_table('property_availability')
    op.drop_table('property_assignments')
    op.drop_index(op.f('ix_mandates_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_index(op.f('ix_buyer_profiles_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
